{
    id: 57,
    logo: null,
    approval_document: null,
    grants: [],
    groups: [
      {
        id: 38,
        name: "E",
        group_type: "e",
        max_children: 12,
        years_from: 1,
        years_to: 3
      },
      {
        id: 39,
        name: "s",
        group_type: "s",
        max_children: 33,
        years_from: 3,
        years_to: 4
      }
    ],
    services: [],
    created_at: "2019-11-27T14:20:53",
    updated_at: "2019-11-27T14:49:42",
    name: "Test Skola",
    school_number: "",
    address: "fdbgffb",
    postal_code: "33445",
    city: "dfvfvfd",
    phone_number1: "355454",
    phone_number2: "",
    email: "",
    fax_number: "",
    mobile_number: "",
    school_type: "",
    website: "",
    emergency_number: "",
    poison_emergency_number: "",
    extra: [],
    identification_number: "",
    max_children: 4
  },
  {
    id: 58,
    logo: null,
    approval_document: null,
    grants: [],
    groups: [],
    services: [],
    created_at: "2019-11-27T14:21:04",
    updated_at: "2019-11-27T14:21:04",
    name: "Test Skola 2",
    school_number: "",
    address: "",
    postal_code: "",
    city: "",
    phone_number1: "",
    phone_number2: "",
    email: "",
    fax_number: "",
    mobile_number: "",
    school_type: "",
    website: "",
    emergency_number: "",
    poison_emergency_number: "",
    extra: [],
    identification_number: "",
    max_children: 4
  }